# Generated by Django 4.2.5 on 2025-09-13 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("driver", "Водитель"), ("client", "Пассажир")],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="profile_image/")),
                (
                    "inn",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxLengthValidator(12),
                            django.core.validators.MinLengthValidator(12),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_license", models.ImageField(upload_to="driver_license/")),
                ("driver_license_face", models.ImageField(upload_to="driver_license/")),
                ("format_license", models.CharField(max_length=8)),
                ("term", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_left", models.ImageField(upload_to="car_image/")),
                ("car_right", models.ImageField(upload_to="car_image/")),
                ("car_front", models.ImageField(upload_to="car_image/")),
                ("car_back", models.ImageField(upload_to="car_image/")),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_photo",
                        to="service_user.personalinfo",
                    ),
                ),
            ],
        ),
    ]
