# Generated by Django 4.2.5 on 2025-09-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "service_user",
            "0002_alter_carphoto_personal_info_alter_personalinfo_user_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="carphoto",
            old_name="car_right",
            new_name="car_in",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="format_license",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="term",
        ),
    ]
