# Generated by Django 4.2.5 on 2025-09-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_user", "0003_rename_car_right_carphoto_car_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="inn",
            field=models.IntegerField(),
        ),
    ]
