# Generated by Django 4.2.5 on 2025-09-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service_user", "0004_alter_profile_inn"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.FileField(upload_to="car_detect/")),
                (
                    "personal_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service_user.personalinfo",
                    ),
                ),
            ],
        ),
    ]
