# Generated by Django 4.2.5 on 2025-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_user", "0005_detectcar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="inn",
            field=models.CharField(max_length=12),
        ),
    ]
